### ISSUE TITLE
Design ตัว Boss

### ISSUE THREAD

**Issue by OHMSIRAPOB** [OHMSIRAPOB/Project-Scratch-25#12]

**Comment by OHMSIRAPOB** [comment]
Design ตัว Boss

1. ตัว Boss ตอนอยู่ในเกม ( Model )
2. ตัว Boss ตอนพูด

**Comment by PoomNattapoom** [comment]
ดีไซน์ตัวบอส 
https://media.discordapp.net/attachments/1017472234836738168/1021451211741868123/pim-alink-pq3-final-boss.gif?width=1408&height=662
