### ISSUE TITLE
Design อุปสรรคต่างๆ

### ISSUE THREAD

**Issue by OHMSIRAPOB** [OHMSIRAPOB/Project-Scratch-25#13]

**Comment by OHMSIRAPOB** [comment]
Design อุปสรรคต่างๆ

1. อุกกาบาต
2. เศษอุกกาบาต
3. ขยะ ( ทั่วไป )
4. ขยะ ( อวกาศ )

**Comment by YotsawatSuki** [comment]
![image](https://user-images.githubusercontent.com/110969388/189700191-5f2c520e-5497-4f14-ad19-38995157a302.png)

![image](https://user-images.githubusercontent.com/110969388/189700219-841cb731-48fb-45ec-ab67-cfe5804e8bd9.png)
เราได้อุกกาบาตมาแล้วเรียบร้อย

**Comment by PoomNattapoom** [comment]
Object ที่จะดีไซน์เพิ่ม

- object อย่างขยะต่างๆ พวกกระป๋อง อะไรประมาณนี้ ที่หลุดออกมาจากโลก
- บอสที่เป็นขยะกลายพันธุ์(อยากได้เวอร์ในเกมและภาพอาร์ตตอนสนทนาถ้าเป็นไปได้นะ)
- ดีไซน์ตัวของผู้เล่นตอนบทสทนา(มีตัวเล่นในเกมแล้ว)
- ขยะอวกาศ
