### ISSUE TITLE
Design UI

### ISSUE THREAD

**Issue by OHMSIRAPOB** [OHMSIRAPOB/Project-Scratch-25#14]
1). UI ระบบเกม
     1. UI หน้า Home 
     2. ปุ่มเริ่มเกม
     3. ปุ่ม UI หน้า Pause เกม
     4. ปุ่ม Home

2). Interface เกม 
     1. หลอด Hp
     2. หลอด Hp Boss
     3. นาฬิกานับถอยหลัง

**Comment by YotsawatSuki** [comment]
![image](https://user-images.githubusercontent.com/110969388/189700786-12b6b269-eb8b-4ed1-aeb6-f34aa29fec03.png)
UI หน้าปกเกม

**Comment by YotsawatSuki** [comment]
![image](https://user-images.githubusercontent.com/110969388/189700959-e99059b8-8158-4046-8ec6-78c62c64060d.png)
เมื่อกดธงเขียวพร้อมเล่น จะมีปุ่มเริ่มเกมอยู่ด้วย

**Comment by YotsawatSuki** [comment]
![image](https://user-images.githubusercontent.com/110969388/189701398-980ae609-8544-4dba-a584-26aeccefed6b.png)
หลังกดปุ่มเริ่มเกมก็จะมีหน้าเลือกด่านโผล่มา ซึ่งมุมล่างซ้ายมีปุ่มกดย้อนมาหน้าปกให้ด้วย

**Comment by YotsawatSuki** [comment]
![image](https://user-images.githubusercontent.com/110969388/189702052-610dacb5-47b0-44fb-8b01-a615c1c35ff3.png)
![image](https://user-images.githubusercontent.com/110969388/189702126-b786c38b-ff5e-4c2b-baa8-ee975316c4d3.png)
![image](https://user-images.githubusercontent.com/110969388/189710301-bf2743a8-d999-406c-91f2-18db48c4171d.png)
เวลาเมื่อกดปุ่มเมนูขึ้นมา ในแต่ละสถานการณ์ เช่น ตอนกล่องบทนำภารกิจที่1 ตอนบทสนทนาตัวละคร และตอน gameplay

**Comment by YotsawatSuki** [comment]
![image](https://user-images.githubusercontent.com/110969388/189710557-945182d1-1fd8-4298-a1bc-0f861b67db26.png)
มุมบนซ้ายคือหลอดเลือด
