### ISSUE TITLE
เนื้อเรื่องในเกม

### ISSUE THREAD

**Issue by OHMSIRAPOB** [OHMSIRAPOB/Project-Scratch-25#16]

**Comment by OHMSIRAPOB** [comment]
เนื้อเรื่องตอนเข้า Mission 1
(ใครสักคนที่ดูเป็นหัวหน้า) :     สวัสดีคุณ ... 
(ใครสักคนที่ดูเป็นหัวหน้า) :     ฉันชื่อ Mrs. Prayat   Chan Ang Kan Phut เป็นหัวหน้าองค์กร Taeng Kwa Dong องค์กรนี้มีเพื่อที่จะดูแลรักษาโลกใบนี้
Mrs. Prayat :     คุณได้รับมอบหมายหน้าที่อันทรงเกียรติ เพราะเนื่องจากสถานการณ์ของโลกมันยากเกินควบคุมแล้ว ขยะล้นโลกและ ทรัพยากรกำลังหมดไป
Mrs. Prayat :     เพราะฉะนั้นคุณได้รับหน้าที่เป็นหัวหน้าของยาน Makhueathet Thot Krop เพื่อที่จะออกสำรวจและเสาะหาดาว Kepler เพราะดาวดวงนี้เหมาะสมกับการย้ายถื่นฐานไปตั้งรกรากให้กลายเป็นดาวโลกดวงใหม่ ทำให้ดาวดวงนั้นดีกว่าโลกของเราและไม่เป็นดั้งที่โลกในปัจจุบันของเรากำลังเผชิญอยู่
Mrs. Prayat :     คุณพร้อมที่จะรับหน้าที่อังทรงเกียรตินี้หรือไม่ 
(ชื่อคนเล่น) :     (พร้อม , พร้อมเหมือนกันแต่เปลี่ยนFont)
Mrs. Prayat :     การสำรวจครั้งนี้มีความสำคัญกับโลกของเราเป็นอย่างมาก เราขอให้คุณปฏิบัติหน้าที่นี้ให้ดีที่สุด
Mrs. Prayat :     ขอให้พลังจงสถิตอยู่กับท่าน !

**Comment by YotsawatSuki** [comment]
เนื้อเรื่องอะ เราอยากได้ส่วนเกริ่นเนื้อเรื่องเพื่อปูพื้นหลังเรื่องราวหน่อยอะ
![image](https://user-images.githubusercontent.com/110969388/189961706-a89c719b-b15a-44e2-9e89-4f19e35e40f4.png)
ก็คือส่วนตรงนี้ที่จะอยู่ก่อนเริ่มบทสนทนา

**Comment by OHMSIRAPOB** [comment]
ได้ๆเดี๋ยวเขียนไปเรื่องย่อให้

**Comment by OHMSIRAPOB** [comment]
โลกที่เราอยู่อาศัยนั้นทรัพยากรเริ่มหมดไปจากโลก รวมถึงมีขยะมากมายที่ไม่สามารถกำจัดได้ทำให้เริ่มไม่สามารถอาศัยอยู่ได้อีกต่อไป ทางองค์กรที่มีชื่อว่า Taeng Kwa Dong ที่เกิดจากการร่วมมือของนานาประเทศทั่วโลก ได้ทำการส่งยานอวกาศ Makhueathet Thot Krop ขึ้นไปสำรวจดาวที่สามารถอาศัยอยู่ได้ ซึ่งมีชื่อดาวเคราะห์ว่า Kepler แต่ระหว่างทางก็มีอุปสรรคมากมายมาขวางทางพวกเขา เรื่องราวจะเป็นอย่างไรโปรดติดตาม (อย่ากด Skip ได้โปรด;-;)

**Comment by OHMSIRAPOB** [comment]
ได้มั้ยๆ @YotsawatSuki
