### ISSUE TITLE
เสนอหัวข้อเกม

### ISSUE THREAD

**Issue by OHMSIRAPOB** [OHMSIRAPOB/Project-Scratch-25#2]

**Comment by OHMSIRAPOB** [comment]
1.อยากทำเกมแนวสู้กับบอส บอสมีสกิลต่างๆมาโจมตีผู้เล่น ส่วนผู้เล่นก็มีคลาสให้เลือก แต่ละคลาสก็มีสกิลแตกต่างกัน ประมาณนี้

**Comment by YotsawatSuki** [comment]
อยากทำเกม 8 bit มุมมอง bird eye view ที่ให้เราได้เดินสำรวจแมปต่างๆ ที่เมื่อเดินสุดขอบก็จะเปลี่ยนสถานที่พื้นหลังเป็นอีกพื้นที่ ส่วนระหว่างพื้นที่หนึ่งๆ จะมีสมบัติซ่อนอยู่ซึ่งต้องให้ผู้เล่นได้สำรวจหา ส่วนมอนเตอร์ยังไม่แน่ใจว่าควรทำดีไหม

**Comment by PoomNattapoom** [comment]
อยากทำเกม แนว 2d platformer เดินผ่านด่าน ผ่านอุปสรรคต่างๆ

**Comment by OHMSIRAPOB** [comment]
โหวตของคนอื่นห้ามโหวตของตัวเอง โดยใช้อิโมจิ

**Comment by OHMSIRAPOB** [comment]
เดินหลบอุปสรรค ทำคะแนนให้ได้มากที่สุด ประมาณๆนี้

**Comment by OHMSIRAPOB** [comment]
เกมแนว 2D หลบสิ่งกีดขวาง มี Boss Fight เป็นด่านๆ
