### ISSUE TITLE
Theme  ที่อยากทำ

### ISSUE THREAD

**Issue by OHMSIRAPOB** [OHMSIRAPOB/Project-Scratch-25#3]

**Comment by YotsawatSuki** [comment]
อยากทำธีมเกี่ยวกับการสอบมิดเทอมที่ผ่านมา แบบเราที่ต่อสู้กับข้อสอบหรือเกรด F อะไรประมาณนั้น ตัวละครก็จะเป็นเราที่เป็นนักศึกษาและศัตรูก็จะเป็นข้อสอบหรือไม่ก็ตัวอักษร F แทนเกรด F

**Comment by PoomNattapoom** [comment]
เป็นธีมแนวอุโมงค์รถไฟใต้ดิน โดยฉากอยู่ในอุโมงค์รถไฟ โดดข้ามสิ่งกีดขวางต่างๆ

**Comment by PoomNattapoom** [comment]
ธีมอวกาศ มีอุปสรรค เป็นอุกกาบาต หรือมอนสเตอร์ สิ่งแปลกปลอมจากอวกาศ
