### ISSUE TITLE
เตรียม Slide 

### ISSUE THREAD

**Issue by OHMSIRAPOB** [OHMSIRAPOB/Project-Scratch-25#4]

**Comment by YotsawatSuki** [comment]
เดี๋ยวเราน่าจะทำหน้าที่ coding โอมทำหน้าเป็น project maneger และภูมิก็ game desize แล้วกัน

**Comment by OHMSIRAPOB** [comment]
โลกที่เราอยู่อาศัยนั้นทรัพยากรเริ่มหมดไปจากโลกรวมถึงมีขยะมากมายที่ไม่สามารถกำจัดได้ทำให้เริ่มไม่สามารถอาศัยอยู่ได้อีกต่อไป ทางองค์กรที่มีชื่อว่า Taeng Kwa Dong ที่เกิดจากการร่วมมือของนานาประเทศทั่วโลก ได้ทำการส่งยานอวกาศ Makhueathet Thot Krop ขึ้นไปสำรวจดาวที่สามารถอาศัยอยู่ได้ ซึ่งมีชื่อดาวเคราะห์ว่า Kepler แต่ระหว่างทางก็มีอุปสรรคมากมายมาขวางทางพวกเขา เรื่องราวจะเป็นอย่างไรต่อไป พบกันในเกมครับ อิอิ 

เนื้อเรื่องในเกมคร่าวๆเอาไว้พูดตอนพรีเซ้น

**Comment by OHMSIRAPOB** [comment]
สวัสดีครับวันนี้กลุ่มผมจะมาพรีเซ้นหัวข้อโครงงาน ในการทำเกมจากโปรแกรม Scatch เกมของเรามีชื่อว่า Kepler Seeker ครับ ที่มาของชื่อก็คือ คำว่า Kepler นั้นเป็นดาวเคราะห์ที่มีแนวโน้มที่จะสามารถอาศัยอยู่ได้ที่มีอยู่จริง ผมเลยมาเล่นคำกับคำว่า Seeker ที่แปลประมาณว่านักแสวงหาหรือนักค้นหา 
ความหมายโดยรวมก็คือ นักแสวงหาดาว Kepler ครับ ตัวเกมจะเป็นแนว Platformer 2D  ผสม Boss Fight เนื้อเรื่องคร่าวๆของเกม โลกที่เราอยู่อาศัยนั้นทรัพยากรเริ่มหมดไปจากโลกรวมถึงมีขยะมากมายที่ไม่สามารถกำจัดได้ทำให้เริ่มไม่สามารถอาศัยอยู่ได้อีกต่อไป 
ทางองค์กรที่เกิดจากการร่วมมือของนานาประเทศทั่วโลก ได้ทำการส่งยานอวกาศขึ้นไปสำรวจดาวที่สามารถอาศัยอยู่ได้ ซึ่งมีชื่อดาวเคราะห์ว่า Kepler แต่ระหว่างทางก็มีอุปสรรคมากมายมาขวางทางพวกเขา ซึ่งอุปสรรคในเกม ก็จะเป็นพวกเศษหิน เศษอุกกาบาต และก็พวกขยะต่างๆที่เกิดจากโลก 
รวมถึงบอสที่เป็นเอเลี่ยนที่กลายพันธุ์จากขยะที่ล้นออกมาจากในโลก
เนื่องจากจุดมุ่งหมายของเกมที่จะให้เกมนี้สะท้อนความเป็นจริงที่โลกนั้นมีขยะจำนวนมากมายทำให้เป็นอุปสรรคและก่อให้เกิดปัญหาต่างๆอีกมากมายเช่นกัน 
เราอยากให้ทุกคนเล็งเห็นถึงปัญหาที่ดูอาจจะเล็กน้อยในสายตาพวกเรา แต่ปัญหาที่ดูเล็กน้อยเหล่านั้น ถ้ามันเกิดด้วยกันเป็นจำนวนมาก ก็จะก่อให้เกิดปัญหา ที่ใหญ่เกินกว่าจะแก้ไขได้
สิ่งที่ผู้เล่นจะได้รับจากเกมนี้ก็คือ ความสนุกสนานที่เราต้องใช้ความพยายามในการผ่านด่านของเกมไปให้ได้ และยังมีเนื้อเรื่องที่ชวนน่าติดตาม และยังทำให้ผู้เล่นเล็งเห็นปัญหาขยะที่มีอยู่ในปัจจุบันอีกด้วย 
การแบ่งงานของพวกเรานะครับ เนื่องจากเพื่อนที่อยู่ในกลุ่มอีกคนเขาน่าจะลาออกไปแล้วแต่ชื่อยังอยู่ในระบบกลุ่มพวกเราเหลือกันแค่3 คน 
โดยแบ่งงานดังนี้ครับ โอห์ม ทำหน้าที่เป็น manager บริหารงานให้ในกลุ่ม ช่วยติดต่อเรื่องงานของเพื่อนๆในกลุ่มแล้วก็ยังช่วยงานของเพื่อนๆในกลุ่ม คอปเตอร์ เป็นคนเขียนโค้ดในเกมให้ออกมาเป็นแบบที่ต้องการ และ ภูมิ ทำหน้าที่เป็น Designer ออกแบบกราฟฟิครวมถึงตัวละครและฉากต่างๆในเกม 
ส่วนตำแหน่ง Tester นั้นเราให้ทุกคนช่วยๆกันทำหน้าที่นี้ครับ

เนื้อหาพรีเซ้นคร่าวๆ

**Comment by OHMSIRAPOB** [comment]
แบ่งกันพูด 3 คน  ลำดับการพูดเปลี่ยนไปตามเนื้อหาในสไลด์
