### ISSUE TITLE
Design ตัวละครในเกม

### ISSUE THREAD

**Issue by OHMSIRAPOB** [OHMSIRAPOB/Project-Scratch-25#6]

**Comment by OHMSIRAPOB** [comment]
Design ตัวละครที่ต้องทำ

1. ตัวละครหลัก ( Model ตอนอยู่ในเกม)
2. ตัวละครหลักเวลาพูดคุย
3. ตัวละคร NPC ณ ตอนพูดคุย

**Comment by YotsawatSuki** [comment]
ตัวละครมนเกมก็จะเป็นยานอวกาศนะ ส่วนตอนพูดคุยก็แบบบทสนทนาเกม rpg

**Comment by YotsawatSuki** [comment]
![image](https://user-images.githubusercontent.com/110969388/189512020-42eb3c33-e07e-4a60-8d95-b183fe06a367.png)
ประมาณนี้เลย

**Comment by YotsawatSuki** [comment]
เราตั้งชื่อตัวหลักด้วยดีมะ

**Comment by OHMSIRAPOB** [comment]
ดีๆเดี๋ยวตั้งให้

**Comment by YotsawatSuki** [comment]
![image](https://user-images.githubusercontent.com/110969388/189700494-e4384a04-db45-4fab-91e1-e7e66b7ccc46.png)
นี่คือตัวผู้เล่นตอนเล่นเกม มีแอนิเมชันอะไรพร้อมเรียบร้อย

**Comment by OHMSIRAPOB** [comment]
สรุปชื่อตัวละครหลักในเกมจะให้ผู้เล่นตั้งชื่อที่อยากใช้ก่อนเข้าเกม
