### ISSUE TITLE
Code ส่วนต่างๆภายในเกม

### ISSUE THREAD

**Issue by OHMSIRAPOB** [OHMSIRAPOB/Project-Scratch-25#7]

**Comment by OHMSIRAPOB** [comment]
โค้ดส่วนต่างๆที่ต้องทำ
1). ระบบเคลื่อนไหว ( ตัวละคร )
     1. การเคลื่อนไหวของตัวละครหลัก

2). ระบบเคลื่อน ( ฉาก , Object ต่างๆ )
     1. การเคลื่อนที่ของอุปสรรคในเกม
     2. การเลื่อนฉากไปทางซ้ายเลื่อยๆ

3). ระบบ UI
     1. Menu ตอนเริ่มเกม
     2. การเพิ่มลดเสียงต่างๆ (เสียงหลัก , เสียงเพลง , เสียงEffect)
     3. กด Start
     4. กด Pause
     5. กด Continue
     6. กด Restart
     7. กด Exit
     8. ปุ่ม Home
     9. กด UI ต่างๆแล้วเปลี่ยนฉาก

4). ระบบ Hp
    1. หลอด  Hp ตัวละครหลัก
    2. หลอด Hp ตัวละคร Boss
    3. การตรวจสอบว่าอุปสรรคมาสัมผัสตัวละครหลักแล้ว Hp ลด
    4. การตรวจสอบว่าอุปสรรคมาสัมผัสตัวละคร Boss แล้ว Hp ลด

5). ระบบยิง
    1. การเคลื่อนไหวของกระสุน
    2. การตรวจสอบว่ากระสุนสัมผัสกับตัวละครหลัก
    3. การตรวจสอบว่ากระสุนสัมผัสกับตัวละคร Boss

6). ระบบนับเวลา
   1. นับเวลาถอยหลัง

7). ระบบการแสดง Interface ตอนตัวละครคุยกัน
   1. Interface ตอนตัวละครคุย
   2. การ Pop up ของบทสนทนา
   3. การ Fade ไปของบทสนทนา
   4. การ Click เพื่อเลื่อนบทสนทนาต่อไป
   5. ตัวเลือกในการตอบของตัวละคร

**Comment by YotsawatSuki** [comment]
เริ่มออกแบบระบบการเคลื่อนที่เสร็จเรียบร้อย เตรียมออกแบบการทรานซิชั่นหน้าสไลด์

**Comment by PoomNattapoom** [comment]
ทำการออกแบบทั้งหมดของเกมเสร็จเรียบร้อย
