### ISSUE TITLE
ฉากและพื้นหลัง

### ISSUE THREAD

**Issue by OHMSIRAPOB** [OHMSIRAPOB/Project-Scratch-25#8]

**Comment by OHMSIRAPOB** [comment]
Design ฉากและพื้นหลัง

1. Background ตอนอยู่ในเกม
2. Background ตอนอยู่หน้า Menu หลัก
3. Background ตอนพูดคุย
4. Background ตอน Game Over
5. Background ตอนจบด่าน
6. Background ตอนจบเกม

**Comment by YotsawatSuki** [comment]
ตอนนี้หารูปพื้นหลังมาหมดล่ะ เดี๋ยวช่วยกันดูว่าได้ไหม

**Comment by YotsawatSuki** [comment]
![188825](https://user-images.githubusercontent.com/110969388/189512618-cc02a5c9-7420-446a-8e98-a703d59f49ca.jpg)
นี่ใช้ตอนอยู่ในเกม

**Comment by YotsawatSuki** [comment]
![Premium Vector _ Abstract hud ui gui future futuristic screen system virtual design](https://user-images.githubusercontent.com/110969388/189512627-d59da5cc-cf78-42fe-a978-0431c816cbb8.jpg)
![Premium Vector _ Abstract hud ui gui future futuristic screen system virtual](https://user-images.githubusercontent.com/110969388/189512630-e49261bd-8e30-4e9f-9937-952c6467f14c.jpg)
สองอันนี้ยังเลือกไม่ได้ แต่ทั้งคู่เอาไปใช้เป็นหน้า menu

**Comment by YotsawatSuki** [comment]
![Download Hallway in spaceship with porthole and camera for free](https://user-images.githubusercontent.com/110969388/189512653-12a07368-5dad-4394-8564-deed03cea485.jpg)
![I need spaceship bedroom background](https://user-images.githubusercontent.com/110969388/189512656-a366d978-3e91-47fb-9f00-53042c219bdf.png)
![Premium Vector _ Spaceship corridor with closed doors and big window or viewport_](https://user-images.githubusercontent.com/110969388/189512658-d69d91ae-3e2f-4325-966d-613a807d64d4.jpg)
พวกนี้เอาไปใช้ตอนบทสนทนา

**Comment by YotsawatSuki** [comment]
ตอน game over ก็พื้นหลังดำเลย
![1268183](https://user-images.githubusercontent.com/110969388/189512678-c1bed39d-cb53-4ba4-bd26-5f7217fa6d4b.jpg)

**Comment by YotsawatSuki** [comment]
![Sci-Fi Background](https://user-images.githubusercontent.com/110969388/189512683-5ebedef1-03d2-4258-836e-83fa8f37c1f8.jpg)
อันนี้ตอนจบด่าน

**Comment by YotsawatSuki** [comment]
![wp3366611](https://user-images.githubusercontent.com/110969388/189512690-31759af9-2580-41ab-b829-306af6c67ddd.jpg)
อันนี้ให้ตอนจบเกมโดยเหมือนสมมุติว่าดาวที่อยู่ในพื้นหลังคือ kepler

**Comment by YotsawatSuki** [comment]
มาติชมพื้นหลังได้นะว่าโอเคไหม?

**Comment by YotsawatSuki** [comment]
และอยากได้ฟ้อนต์ด้วยๆ เอาไปประกอบหน้าจอต่างๆ ตอนนี้หายังไม่เท่าไหร่เลย

**Comment by YotsawatSuki** [comment]
![galaxy-pixel-art](https://user-images.githubusercontent.com/110969388/189513249-dbd630a8-ebfe-445d-bd7f-818a861e162c.gif)
![istockphoto-1208374725-170667a](https://user-images.githubusercontent.com/110969388/189513251-e8464f24-c835-4c99-97d1-c6dfc4e4431f.jpg)
![1140964](https://user-images.githubusercontent.com/110969388/189513257-3e0288d7-8687-42c3-8f2b-e87cd4f52528.png)
ได้มาเพิ่มอีก 3 รูป เอามาประกอบการตัดสินใจ

**Comment by YotsawatSuki** [comment]
![image](https://user-images.githubusercontent.com/110969388/189526951-ff9c8d5c-0c8f-4645-bac6-df078c3a3dc1.png)

**Comment by YotsawatSuki** [comment]
![image](https://user-images.githubusercontent.com/110969388/189526970-af50b0f6-2ef7-46a3-8a0e-a3202a24d92d.png)

**Comment by YotsawatSuki** [comment]
![image](https://user-images.githubusercontent.com/110969388/189526986-31261cb1-1b7a-460c-8bd3-ed3ba4609574.png)

**Comment by YotsawatSuki** [comment]
![image](https://user-images.githubusercontent.com/110969388/189526998-237a6156-7363-4d84-9f4d-cd093f98a3a0.png)

**Comment by YotsawatSuki** [comment]
สภาพเกมในปัจจุบัน
